### ISSUE TITLE
Consider using Armin's snaek library

### ISSUE THREAD

**Issue by davidblewett** [jbaiter/python-rust-fst#5]
Armin Ronacher has factored out the necessary bits of building wheels that use Rust, but do not need to link to libpython into a library called snaek: https://github.com/mitsuhiko/snaek . It might be a better alternative than carrying that maintenance burden here.

**Comment by jbaiter** [comment]
While the library certainly looks very well done, I don't know how much it really buys us at this point. From a cursory glance over the code, it currently only provides support for setuptools integration (which we're already using, based on some of Armin's earlier code), some rudimentary error handling as well as header files generated by `cbindgen`.

The library currently implements its own error handling which has some more features (like more fine-grained exceptions) and works quite well. The headers are also pretty much done and won't change much in the future, except if the upstream library does a fundamental refactoring.

So I probably won't put this as a high-priority issue on my to-do-list, but if you like, I'd have no problem with a PR that replaces our own setuptools integration with snaek's and uses the library to automatically generate the header file.

**Comment by messense** [comment]
Maybe you should take a look at https://github.com/getsentry/milksnake
