### ISSUE TITLE
Upstream file version changed

### ISSUE THREAD

**Issue by davidblewett** [jbaiter/python-rust-fst#6]
It appears the on-disk version of an FST file changed since the last release of this package:

```
In [1]: import rust_fst

In [2]: fst_map = rust_fst.Map('output.fst')
---------------------------------------------------------------------------
TransducerError                           Traceback (most recent call last)
<ipython-input-2-5569acb18f20> in <module>()
----> 1 fst_map = rust_fst.Map('output.fst')

~/.virtualenvs/proc_lookup/lib/python3.6/site-packages/rust_fst/map.py in __init__(self, path, _pointer)
    174         if path:
    175             s = checked_call(lib.fst_map_open, self._ctx,
--> 176                              ffi.new("char[]", path.encode('utf8')))
    177         else:
    178             s = _pointer

~/.virtualenvs/proc_lookup/lib/python3.6/site-packages/rust_fst/lib.py in checked_call(fn, ctx, *args)
     67     if err_type is None:
     68         err_type = FstError
---> 69     raise err_type(msg)

TransducerError: Error opening FST: expected API version 1, got API version 2. It looks like the FST you're trying to open is either not an FST file or it was generated with a different version of the 'fst' crate. You'll either need to change the version of the 'fst' crate you're using, or re-generate the FST.

```

I tried building the package locally using the latest nightly Rust, but got this:

```
In [1]: import rust_fst

In [2]: fst_map = rust_fst.Map('output.fst')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-5569acb18f20> in <module>()
----> 1 fst_map = rust_fst.Map('output.fst')

~/.virtualenvs/proc_lookup/lib/python3.6/site-packages/rust_fst/map.py in __init__(self, path, _pointer)
    174         if path:
    175             s = checked_call(lib.fst_map_open, self._ctx,
--> 176                              ffi.new("char[]", path.encode('utf8')))
    177         else:
    178             s = _pointer

~/.virtualenvs/proc_lookup/lib/python3.6/site-packages/rust_fst/lib.py in checked_call(fn, ctx, *args)
     55 def checked_call(fn, ctx, *args):
     56     res = fn(ctx, *args)
---> 57     if not ctx.has_error:
     58         return res
     59     type_str = ffi.string(ctx.error_type).decode('utf8')

ValueError: got a _Bool of value 80, expected 0 or 1

```

Also, in order to build it, I had to do `rustup default nightly && pip install --no-cache-dir . && rustup default stable` because it appears `pip` copies the code to `/tmp` before building, so the `rustup` override didn't work. I built with: `rustc 1.24.0-nightly (687d3d15b 2018-01-02)`.

**Comment by davidblewett** [comment]
I built the FST file using the `fst-bin` crate, version `0.3.0`.

**Comment by BurntSushi** [comment]
Yeah the latest release of `fst` bumped the API version of the format on disk itself, which means:

```
  fst<=0.2 cannot read FSTs generated by fst>=0.3.
  fst>=0.3 can read FSTs generated by fst<=0.2.
```

This commit has details: https://github.com/BurntSushi/fst/commit/60feb1abf2d8212f0f8813dedd31e8c87a39f081

On another note, I'm happy to see that you got a good failure mode. :-) Yay for planning ahead!

**Comment by jbaiter** [comment]
Thanks for reporting this @davidblewett! I just pushed a fix that bumps the upstream version to 0.3 (for the `fst` crate) and 0.2 (for the `fst_regex` and `fst_levenshtein` crates). I only tested it with a 0.2 FST that I had lying around, could you maybe give it a spin with your 0.3 FST?

**Comment by davidblewett** [comment]
@jbaiter Looks good.

**Comment by davidblewett** [comment]
@jbaiter Can I bug you for a release of this fix? I've been migrating a project to inside a container and don't have an easy way of distributing the binary wheel I built manually.

**Comment by jbaiter** [comment]
I'll try to get around to it this weekend, there's still a pending bug on non-amd64 platforms, since a Rust struct from the crate is passed directly over the ABI, and on i686 the order of the struct fields seems to be switched. I'll have to find a way to efficiently address that issue (ideally without having to allocate an extra struct...).
